import "./globals.css";
import CoursePlanner from "./course-planner";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient-to-br from-blue-50 to-purple-100 border`}
      >
       
        {children}
      </body>
    </html>
  );
}
